version: "3.9"

services:

  main:
    container_name: main
    build:
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    build: ./src/db/
    command: postgres -c logging_collector=on
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin: